module.exports = [
    {
        push_token: 'test1',
        email_address: 'amin.aghabeiki@gmail.com',
        mobile_number: 127623452,
        firstname: 'amin1',
        lastname: 'aghabeiki',
        gender: 1,
        date_of_birth: new Date('1987/09/25').toISOString(),
        passport_expiry: '2020/03/04',
        language: 'EN',
        currency: 'RM',
        city: 'kuala lumpur',
        country: 'MY',
        is_member: true,
        flight_stats_notification: true,
        app_version: '5',
        device_type: 'IOS',
        device_os_version: '0',
        device_locale: 'en-us',
        anyFlights: {
            pnr: 'ABC1',
            airline_iata_code: 'DD',
            flight_number: '1234',
            origin: 'KUL',
            destination: 'PKG',
            STD: new Date('2017/1/1').toISOString(),
            STA: new Date('2017/1/2').toISOString(),
            STDOrg: new Date('2017/1/1').toISOString(),
            STAOrg: new Date('2017/1/2').toISOString(),
            departure_gate: '12',
            arrival_gate: '13'
        },
        anyBooking: {
            pnr: 'ABC1',
            booking_no: 'ABC 123',
            airline_iata_code: 'DD',
            booking_datetime: new Date(2017, 1, 1).toISOString(),
            passenger_count: 1,
            adult_count: 1,
            child_count: 0,
            gender_male: 1,
            gender_female: 0,
            gender_others: 0,
            currency: 'MYR',
            amount: 100.1,
            status: 'CONFIRM',
            appengine_region: 'asia',
            appengine_citylatlong: '3.126677, 101.671881',
            appengine_city: 'Kuala Lumpur',
            appengine_country: 'Malaysia'
        }
    },
    {
        push_token: 'test2',
        email_address: 'amin.aghabeiki@gmail.com',
        mobile_number: 127623452,
        firstname: 'amin2',
        lastname: 'aghabeiki',
        gender: 1,
        date_of_birth: new Date('1987', '03', '21').toISOString(),
        passport_expiry: '2020/03/04',
        language: 'EN',
        currency: 'RM',
        city: 'kuala lumpur',
        country: 'IR',
        is_member: true,
        flight_stats_notification: true,
        app_version: '0',
        device_type: 'android',
        device_os_version: '0',
        device_locale: 'en-us',
        anyFlights: {
            pnr: 'ABC2',
            airline_iata_code: 'DD',
            flight_number: '1234',
            origin: 'KUL',
            destination: 'IKA',
            STD: new Date('2017/1/1').toISOString(),
            STA: new Date('2017/1/2').toISOString(),
            STDOrg: new Date('2017/1/1').toISOString(),
            STAOrg: new Date('2017/1/2').toISOString(),
            departure_gate: '12',
            arrival_gate: '13'
        },
        anyBooking: {
            pnr: 'ABC2',
            booking_no: 'ABC 123',
            airline_iata_code: 'DD',
            booking_datetime: new Date(2017, 1, 1).toISOString(),
            passenger_count: 3,
            adult_count: 1,
            child_count: 2,
            gender_male: 1,
            gender_female: 0,
            gender_others: 0,
            currency: 'MYR',
            amount: 100.1,
            status: 'CONFIRM',
            appengine_region: 'asia',
            appengine_citylatlong: '3.126677, 101.671881',
            appengine_city: 'Kuala Lumpur',
            appengine_country: 'Malaysia'
        }
    },
    {
        push_token: 'test3',
        email_address: 'amin.aghabeiki@gmail.com',
        mobile_number: 127623452,
        firstname: 'amin3',
        lastname: 'aghabeiki',
        gender: 1,
        date_of_birth: new Date('1987/3/21').toISOString(),
        passport_expiry: new Date('2017/08/25').toISOString(),
        language: 'EN',
        currency: 'RM',
        city: 'kuala lumpur',
        country: 'MY',
        is_member: true,
        flight_stats_notification: true,
        app_version: '0',
        device_type: 'android',
        device_os_version: '0',
        device_locale: 'en-us',
        anyFlights: {
            pnr: 'ABC',
            airline_iata_code: 'DD',
            flight_number: '1234',
            origin: 'KUL',
            destination: 'IKA',
            STD: new Date('2017/1/1').toISOString(),
            STA: new Date('2017/1/2').toISOString(),
            STDOrg: new Date('2017/1/1').toISOString(),
            STAOrg: new Date('2017/1/2').toISOString(),
            departure_gate: '12',
            arrival_gate: '13'
        },
        anyBooking: {
            pnr: 'ABC',
            booking_no: 'ABC 123',
            airline_iata_code: 'DD',
            booking_datetime: new Date(2017, 1, 1).toISOString(),
            passenger_count: 2,
            adult_count: 2,
            child_count: 0,
            gender_male: 1,
            gender_female: 1,
            gender_others: 0,
            currency: 'MYR',
            amount: 100.1,
            status: 'CONFIRM',
            appengine_region: 'asia',
            appengine_citylatlong: '3.126677, 101.671881',
            appengine_city: 'Kuala Lumpur',
            appengine_country: 'Malaysia'
        }
    }
]